INSERT INTO comment (comment_id, comment_title, comment_slug, comment_detail, comment_image, comment_tags, comment_status, comment_published, comment_created, comment_updated) VALUES (1, 'This is title one', 'this-is-title-one', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mattis, lectus vitae faucibus elementum, erat lorem maximus nulla, at condimentum nulla nibh a magna. Donec rutrum magna non mauris sodales pharetra. Duis ullamcorper augue at dolor lacinia sodales. Quisque consectetur magna in justo pulvinar placerat. Etiam eget arcu ut eros auctor porta sed a est. Curabitur sed neque eu sapien interdum vehicula. Aliquam vel finibus eros. Praesent auctor neque luctus, ultricies risus ut, vulputate lacus. Donec commodo elit non mauris congue feugiat. Nam eu purus porta, pulvinar justo vel, tempus augue. Duis rutrum augue justo, at sodales magna euismod nec. Vestibulum vel pretium velit. Cras mollis ligula nec odio tincidunt auctor. Cras faucibus consectetur ullamcorper.', 'https://www.google.com.ph/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png', '[\"one\", \"two\"]', 'PENDING', null, '2018-02-15 05:10:57', '2018-02-15 05:10:57');

INSERT INTO comment (comment_id, comment_title, comment_slug, comment_detail, comment_image, comment_tags, comment_status, comment_published, comment_created, comment_updated) VALUES (2, 'This is title two', 'this-is-title-two', 'Nulla vitae urna leo. Vivamus nec ante quis purus bibendum posuere. Duis ullamcorper elementum erat quis aliquet. Morbi id euismod nunc, eget pharetra nibh. In semper malesuada mi, id tempus mi vulputate id. Fusce pharetra lacinia nibh eget vehicula. Donec sed felis vitae velit vulputate sollicitudin id eget leo. Fusce molestie, neque eget mollis auctor, tellus augue mollis eros, vitae eleifend leo dolor ut lectus.', 'https://www.google.com.ph/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png', '[\"two\", \"three\"]', 'REVIEW', null, '2018-02-15 05:10:57', '2018-02-15 05:10:57');

INSERT INTO comment (comment_id, comment_title, comment_slug, comment_detail, comment_image, comment_tags, comment_status, comment_published, comment_created, comment_updated) VALUES (3, 'This is title three', 'this-is-title-three', 'Integer gravida venenatis lobortis. Vestibulum vulputate turpis id est tincidunt, ut interdum risus porttitor. Etiam aliquet at felis ac vehicula. Aenean in felis in eros convallis rhoncus id quis libero. Vivamus rhoncus hendrerit porta. Ut egestas fermentum urna, in imperdiet odio hendrerit vitae. In suscipit enim eget pellentesque imperdiet. Etiam facilisis tellus in mauris sagittis volutpat. Cras in orci maximus, ullamcorper mauris porta, mattis neque. Etiam ligula felis, mollis id magna ultricies, convallis gravida felis.', 'https://www.google.com.ph/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png', '[\"three\", \"four\"]', 'PUBLISHED', '2018-02-15 05:10:57', '2018-02-15 05:10:57', '2018-02-15 05:10:57');

INSERT INTO comment (comment_id, comment_title, comment_slug, comment_detail, comment_image, comment_tags, comment_status, comment_published, comment_created, comment_updated) VALUES (4, 'This is title four', 'this-is-title-four', 'Quisque dignissim fringilla tincidunt. Nulla facilisi. Morbi tincidunt tortor tincidunt dui bibendum, ornare suscipit ante condimentum. Aliquam erat volutpat. Etiam a nisi rhoncus, feugiat nulla sit amet, pellentesque nulla. Donec sit amet massa eu metus ultricies consequat. Vestibulum aliquam ullamcorper fermentum.', 'https://www.google.com.ph/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png', '[\"four\", \"five\"]', 'PUBLISHED', '2018-02-15 05:10:57', '2018-02-15 05:10:57', '2018-02-15 05:10:57');

INSERT INTO comment (comment_id, comment_title, comment_slug, comment_detail, comment_image, comment_tags, comment_status, comment_published, comment_created, comment_updated) VALUES (5, 'This is title five', 'this-is-title-five', 'Proin sed orci tincidunt, scelerisque dolor sit amet, viverra tellus. Sed dapibus, tortor a gravida vehicula, enim felis ullamcorper est, eget tincidunt est leo vel nibh. Curabitur et erat tristique, vehicula leo non, iaculis felis. Sed libero sapien, aliquet vitae tellus ut, rhoncus sodales lacus. Nam fringilla lacus id urna maximus, in placerat leo gravida. Nunc lorem ex, malesuada et est eu, placerat congue massa. Donec ultrices lacus quis metus sollicitudin semper. Nullam lorem neque, bibendum a elit nec, molestie ultrices mi. In imperdiet bibendum maximus.', 'https://www.google.com.ph/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png', '[\"five\", \"six\"]', 'PUBLISHED', '2018-02-15 05:10:57', '2018-02-15 05:10:57', '2018-02-15 05:10:57');

INSERT INTO comment_profile (comment_id, profile_id) VALUES (1, 1), 
(2, 1), 
(3, 1), 
(4, 1), 
(5, 1);